# Generated by Django 4.0.3 on 2022-03-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hows_how_alter_typses_types_alter_whens_when_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('feedback', models.TextField(max_length=2000)),
            ],
        ),
    ]
